### PR TITLE
Fixing height of boxes on roth contributions

### PR DESCRIPTION
**Pull request by line47**
screen shot 2018-09-17 at 9 11 53 am

### CODE REVIEW

**Comment by line47** [comment]
@Lapedra or @chachi69 can one of you all review 👍

**Comment by Lapedra** [comment]
Is there a way to align the title to the baseline, for instance, "Roth Contributions" sits on the baseline or aligns with "contributions?" So that the paragraph is aligned.

**Comment by line47** [comment]
Something like this?
screen shot 2018-09-18 at 11 51 23 am

**Comment by KishaT** [comment]
@line47 This is one of the pages where the text does not align under the boxes above. See your example at the top of this page. Thanks.

**Comment by line47** [comment]
This should be fixed now @KishaT

**Pull request merged**
