### PR TITLE
Homepage v.10 with KT edits

### PR DESCRIPTION
**Pull request by chachi69**
Still needed: functionality for `Our funds at a glance`.

### CODE REVIEW

**Comment by chachi69** [comment]
image

**Comment by chachi69** [comment]
image

**Comment by chachi69** [comment]
@Lapedra It needs iterating on, but it will be easier to do so with it on staging.

**Comment by Lapedra** [comment]
Hey! For the most part, it looks pretty good. I'd like to see it on the staging website to test the functionality and the look in the browser. Let me know when that's ready.

**Comment by Lapedra** [comment]
I'm on staging, but it's showing up really wonky.

**Pull request merged**
