### PR TITLE
Based on LP's Being a BPA design

### PR DESCRIPTION
**Pull request by chachi69**
being-bpa

### CODE REVIEW

**Comment by chachi69** [comment]
@Lapedra I will merge now so that you can preview a "live" sample.

**Comment by Lapedra** [comment]
Two things are missing which is the light blue bar with the title "You'll need these items to manage your account" and then four items in blue. Also, right above that is a paragraph titled "BPA Welcome Letter." That is missing too. Please review the pdf again for clarity. Thank! Looks good!

**Comment by chachi69** [comment]
@Lapedra The four items in blue were an oversight but I intentionally omitted "BPA Welcome Letter" because it does not appear in the [Google doc](https://docs.google.com/document/d/1_7dCDnb_8gF5aMg9a-Q_vc7QjsyXjgV9pZUhZWO63t8/edit?usp=sharing). In general the Gdoc lined up with your design, except for the "BPA Welcome Letter".  I erred on the side of the Gdoc since that comes from the writers. Also, I think BPA is an internal-only abbreviation.

**Comment by Lapedra** [comment]
Ok, cool. Once, we add the blue items, I think it’ll break up the dark blue a bit. Right now, it’s heavg. Also, I’m working on appropriate icona as I mentioned. We’ll get feedback from the team and move forward.

**Pull request merged**
