### PR TITLE
Create expense-ratio.md

### PR DESCRIPTION
**Pull request by PamGit2715**
I've just created a new file called Expense Ratio under Manage Your Life Changes.

### CODE REVIEW

**Comment by Lapedra** [comment]
I don't see the file. What am I missing?

**Comment by line47** [comment]
Great job @PamGit2715 👍 

@Lapedra if you click on the `files changed 1` at the top you will see the updates. :) 
https://github.com/frtib/tsp-redesign/pull/60/files

**Comment by line47** [comment]
For new content like this - who would need to review this before we merge it in?

**Comment by chachi69** [comment]
@JamelleWT have you conducted your QA on this content?

**Comment by JamelleWT** [comment]
@chachi69 not yet. Working on it.

**Comment by JamelleWT** [comment]
@line47 can you add in line comments to the Github doc html style or do you just have to reference the lines in your comments?

**Pull request merged**
